version: "3.9"
   
services:
  pg_db:
    container_name: postgres
    image: postgres
    volumes:
      - data:/var/lib/postgresql/data
    env_file:
      - ./env_files/.env.pg_db
  web:
    container_name: django_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes: 
      - ./:/code
    command: >
      sh -c "python manage.py collectstatic --noinput &&
            python manage.py makemigrations && 
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - ./env_files/.env.django_app
    depends_on:
      - pg_db

volumes:
  data:
