# Generated by Django 3.2 on 2022-01-14 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolname', models.CharField(max_length=20)),
                ('maxstudents', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Schools Schema',
                'ordering': ['schoolname'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20, verbose_name='First Name')),
                ('lastname', models.CharField(max_length=20, verbose_name='Last Name')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolsmanager.school')),
            ],
            options={
                'verbose_name': 'Students Schema',
                'ordering': ['firstname'],
            },
        ),
    ]
