# Generated by Django 3.2 on 2022-01-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolsmanager', '0002_auto_20220115_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.UUIDField(null=True, unique=True, verbose_name='Student Identification Number'),
        ),
    ]
