# Generated by Django 3.2 on 2022-01-18 10:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schoolsmanager', '0003_student_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Student Identification Number'),
        ),
    ]
