# Generated by Django 3.2 on 2022-01-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolsmanager', '0005_alter_student_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=0, verbose_name="Student's Age"),
        ),
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=models.CharField(default='Empty', max_length=20, verbose_name='Nationality'),
        ),
    ]
