# Generated by Django 3.2 on 2022-01-19 09:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolsmanager', '0006_auto_20220119_0830'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
        migrations.AlterField(
            model_name='school',
            name='maxstudents',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Maximum Number of Students Allowed'),
        ),
        migrations.AlterField(
            model_name='student',
            name='nationality',
            field=models.CharField(default='', max_length=20, verbose_name='Nationality'),
        ),
    ]
