# Generated by Django 3.2 on 2022-01-19 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolsmanager', '0007_auto_20220119_0957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': 'Schools Schema'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Students Schema'},
        ),
    ]
