# Generated by Django 3.2 on 2022-01-19 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolsmanager', '0008_auto_20220119_1004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
    ]
