# Generated by Django 3.2 on 2022-01-20 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolsmanager', '0009_auto_20220119_1012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['schoolname'], 'verbose_name': 'Schools Schema'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['firstname'], 'verbose_name': 'Students Schema'},
        ),
    ]
