# Generated by Django 3.2 on 2022-01-20 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolsmanager', '0010_auto_20220120_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(default='Empty', max_length=20),
            preserve_default=False,
        ),
    ]
