# Generated by Django 3.2 on 2022-01-20 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolsmanager', '0011_alter_student_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='schoolname',
            field=models.CharField(max_length=20, unique=True, verbose_name='School Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
